name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Input File Name'
        required: true
        default: 'test.csv'
jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: 'Cleanup repo'
        run: |
         cd 'C:\Program Files'
         rm -rf ${{inputs.repo-name}}
